# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('position', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
