# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-05 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_officer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPost',
            new_name='NewsPost',
        ),
    ]
