# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_album_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='number',
            new_name='category',
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='Album', max_length=128),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
