# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170813_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='category',
        ),
    ]
