# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-20 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='body',
            field=models.TextField(max_length=256),
        ),
    ]
