# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-20 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170820_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredmember',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
