# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-03 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170820_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
